from: technologyadvice/node-build:4
services:
  - dynamo:
      from: modli/dynamodb
      persist: false
before: |
  export MODLI_DYNAMODB_HOST=http://$DYNAMO_PORT_8000_TCP_ADDR:8000
tasks:
  env: env
  clean: npm run clean
  install: npm install
  mocha: npm run mocha
  test: npm run test
  cover: npm run cover
  lint: npm run lint
  build: npm run build